all: \
    src/404.html \
    src/index.html \
    src/cbg/index.html \
    src/lgw/index.html
src/cbg/index.js: \
    src/cbg/board.ts \
    src/cbg/canvas.ts \
    src/cbg/data.ts \
    src/cbg/hex_tile.ts \
    src/cbg/number_label.ts \
    src/cbg/sprite.ts
src/lgw/index.js: \
    src/lgw/bullet.ts \
    src/lgw/canvas.ts \
    src/lgw/enemy.ts \
    src/lgw/game.ts \
    src/lgw/player.ts \
    src/lgw/sprite.ts
