[[headers]]
for = "/*"
[headers.values]
# unsafe-inline for KaTeX
Content-Security-Policy = "default-src 'self'; style-src 'self' 'unsafe-inline'"
Permissions-Policy = "interest-cohort=()"
Referrer-Policy = "no-referrer"
X-Content-Type-Options = "nosniff"
X-Frame-Options = "SAMEORIGIN"
