[[headers]]
for = "/*"
[headers.values]
Content-Security-Policy = "default-src https:"
Permissions-Policy = "interest-cohort=()"
Referrer-Policy = "no-referrer"
X-Content-Type-Options = "nosniff"
X-Frame-Options = "SAMEORIGIN"
