#!/usr/bin/env bash

set -euo pipefail
IFS=$'\n\t'

server=
end() {
    kill "$server"
    echo " server stopped."
    exit
}
trap end INT

$EDITOR .

static &> /dev/null &
server="$!"
sleep 0.5 && open "http://localhost:8080" &

while true; do
    find . -not -path "*.git*" | entr -cd make || [[ "$?" == 2 ]]
done
