#!/usr/bin/env sh

set -euo pipefail
IFS=$'\n\t'
PATH="node_modules/.bin:$PATH"

server=
end() {
    kill "$server"
    echo " server stopped."
    exit 0
}
trap end INT

http-server src &> /dev/null &
server="$!"
sleep 0.5 && open "http://localhost:8080" &

while true; do find . \
    -not -path "*.git*" \
    -a -not -path "*node_modules*" \
    | entr -d make || [[ "$?" == 2 ]]
done
