#!/usr/bin/env sh

set -euo pipefail
IFS=$'\n\t'

cd "$(dirname "$0")/.."

protocol="http"
domain="azdavis.xyz"

echo "
base/favicon.png
base/touch-icon.png
" | while read f; do
    [[ -z "$f" ]] && continue
    curl -fsSL "$protocol://$domain/$f" > "src/$f"
done
